// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUP7hQpS-lF7OhQt2TyBf4MrkfpOZrqSY',
    appId: '1:915401191752:android:11d70ebd3e2f2f538f037d',
    messagingSenderId: '915401191752',
    projectId: 'fir-flutter-codelab-f8220',
    storageBucket: 'fir-flutter-codelab-f8220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC49rgByI62x1HUrLEPCfrd-fk1oHExFus',
    appId: '1:915401191752:ios:860f457e6393cc008f037d',
    messagingSenderId: '915401191752',
    projectId: 'fir-flutter-codelab-f8220',
    storageBucket: 'fir-flutter-codelab-f8220.appspot.com',
    iosClientId: '915401191752-3d4hams0jln19441csi416kb5qbj586a.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
